name: Deno Deploy

on:
  push:
    branches:
      - main # Trigger on pushes to main
  pull_request:
    branches:
      - main # Trigger on PRs targeting main (for preview deployments)
  repository_dispatch:
    types: [trigger-deno-deploy]

jobs:
  deploy:
    name: Deploy to Deno Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to checkout the repository
      deployments: write # Needed for GitHub Actions deployment
      actions: write # Needed for GitHub Actions

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Create import map
        run: |
          echo '{
            "imports": {
              "@std/": "https://deno.land/std@0.212.0/"
            }
          }' > packages/permit2-rpc-server/import_map.json

      - name: Setup deployctl
        uses: denoland/setup-deployctl@v1
        with:
          version: 1.4.0

      - name: Deploy to Deno Deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DENO_DEPLOY_PROJECT: permit2-rpc-proxy
        run: |
          cd packages/permit2-rpc-server && \
          deployctl deploy --project=permit2-rpc-proxy \
            --prod \
            --import-map=import_map.json \
            src/deno-server.ts \
            --exclude=node_modules \
            --exclude=lib \
            --exclude=.git \
            --exclude=.github \
            --exclude=scripts
