name: Deno Deploy

on:
  push:
    branches:
      - main # Trigger on pushes to main
  pull_request:
    branches:
      - main # Trigger on PRs targeting main (for preview deployments)
  repository_dispatch:
    types: [trigger-deno-deploy]

jobs:
  deploy:
    name: Deploy to Deno Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to checkout the repository
      deployments: write # Needed for GitHub Actions deployment
      actions: write # Needed for GitHub Actions

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Deploy to Deno Deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINKING_MODE: github
        run: |
          deno install --allow-read --allow-write --allow-env --allow-net --allow-run --no-check -f https://deno.land/x/deploy/deployctl.ts
          export PATH="/home/runner/.deno/bin:$PATH"
          deployctl deploy --project=permit2-rpc-proxy packages/permit2-rpc-server/src/deno-server.ts \
            --exclude=node_modules \
            --exclude=lib \
            --exclude=.git \
            --exclude=.github \
            --exclude=scripts
